### PR TITLE
Propose solution for parametrized queries

### PR DESCRIPTION
**Pull request by alexcocia**
Proposed for Issue #91

### CODE REVIEW

**Comment by alexcocia** [comment]
Improved solution. Tested previous version and not working on heavy stress cases

**Comment by alexcocia** [comment]
Hello!. This solution is returning an driver.ErrSkip error, handled by the standard database/sql package, and thus your lib might now implement the standard database/sql package correctly (not just ignoring the parameters provided) #91

**Comment by akhilravuri1** [comment]
Hi @alexcocia 

I will test this pull request and merge it.

Yes, we know that the standard database/sql package does not ignore parameters. 
But we don't have an option to provide the DirectExecute using the sql package so we decided to use this in that way.
Anyway if you want to pass parameters in Query() API you can pass it using db.Prepare() and st.Query().

Thanks,
Akhil

**Comment by alexcocia** [comment]
Any chance for merging this? nearly 6 months passed.
Solution provided check if any args is provided, and instead of forgetting them, it handles such a way that sql will execute the prepareStmt.. It will only affecto when args provided.
Is there any other reason for not merging it?

**Comment by akhilravuri1** [comment]
Hi @alexcocia 

If the user has passed the arguments then these changes will return any error?

Thanks,
Akhil

**Comment by alexcocia** [comment]
Only when parameters are provided, it returns a controlled error notifying that it is not implementing the Queryer interface of database/sql. In this case, DB.Query executes the full prepare + execute + close  instead

The ErrSkip is only returned when parameters are provided, which is providing an error anyway. But this time it is not managed

```
// Queryer is an optional interface that may be implemented by a Conn.
//
// If a Conn implements neither QueryerContext nor Queryer,
// the sql package's DB.Query will first prepare a query, execute the statement,
// and then close the statement.
//
// Query may return ErrSkip.
//
// Deprecated: Drivers should implement QueryerContext instead.
type Queryer interface {
	Query(query string, args []Value) (Rows, error)
}
```

**Comment by akhilravuri1** [comment]
Hi @alexcocia 

Please give me 1 day. I will update you.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Sorry for the delay...code looks clean and it passes all the test cases.
Thanks for the contribution.

**Pull request merged**
