### PR TITLE
DECFLOAT and XML support for SELECT query

### LINKED ISSUE #53: unsupported column type -370 (XML datatype)
- os Version: Windows 10
- cli-driver Version: 11.1
- Db2 Server Version: 11.5.0.1077
- go Version: 1.13.5
- go env:
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sdelacruz\AppData\Local\go-build
set GOENV=C:\Users\sdelacruz\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\sdelacruz\Documents\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\sdelacruz\Documents\go\src\sdi\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\SDELAC~1\AppData\Local\Temp\go-build970289982=/tmp/go-build -gno-record-gcc-switches
```

Steps to Reproduce:

1. Select a column with datatype XML

### LINKED ISSUE #54: unsupported column type -360 (DECFLOAT datatype)
- os Version: Windows 10
- cli-driver Version: 11.1
- Db2 Server Version: 11.5.0.1077
- go Version: 1.13.5
- go env:
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sdelacruz\AppData\Local\go-build
set GOENV=C:\Users\sdelacruz\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\sdelacruz\Documents\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\sdelacruz\Documents\go\src\sdi\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\SDELAC~1\AppData\Local\Temp\go-build970289982=/tmp/go-build -gno-record-gcc-switches
```

Steps to Reproduce:

1. Select a column with datatype DECFLOAT

### PR DESCRIPTION
**Pull request by xhit**
Fix #53 
Fix #54

### CODE REVIEW

**Comment by xhit** [comment]
This PR was tested in Windows and Linux.

Finished work.

PTAL @akhilravuri1

**Comment by akhilravuri1** [comment]
Hi @xhit 

SQL_DECFLOAT C type is SQL_C_CHAR
and SQL_XML c type is SQL_C_BINARY

please check this doc https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0000526.html

Thanks,
Akhil

**Comment by xhit** [comment]
Updated SQL_XML like SQL_C_BINARY

**Comment by xhit** [comment]
Updated SQL_DECFLOAT is SQL_C_CHAR

**Comment by xhit** [comment]
I will close this PR because you made same corrections for DECFLOAT in commit 7c8def0c41322510bcffb74036797fe471ad3afd

New merge for XML support only will be created.

**Pull request closed without merging**
