### PR TITLE
Installer files are readonly - make sure the user has permission to write 

### PR DESCRIPTION
**Pull request by smuda**
When I tried to run the client installer setup.go I got some errors:
```
john$ go run setup.go 
darwin
macos64_odbc_cli.tar.gz
Downloading...
download successful
Creating directory : clidriver/
Creating directory : clidriver/bin/
Creating directory : clidriver/bnd/
Creating directory : clidriver/cfg/
Creating directory : clidriver/cfgcache/
Creating directory : clidriver/conv/
Creating directory : clidriver/db2dump/
Untarring : clidriver/db2profile
Creating directory : clidriver/include/
Creating directory : clidriver/lib/
Creating directory : clidriver/license/
Creating directory : clidriver/msg/
Creating directory : clidriver/msg/en_US.iso88591/
Untarring : clidriver/msg/en_US.iso88591/db2adm.mo
open clidriver/msg/en_US.iso88591/db2adm.mo: permission denied
exit status 1
```

After messing around I realized that all files created was readonly, even by the user. I've added a couple of lines to make sure that the user has write permissions to the created files.

### CODE REVIEW

**Comment by akhilravuri1** [comment]
why you want write permission to clidriver folder

**Comment by smuda** [comment]
Otherwise the untarring would not complete... :-) 

But as I wrote in #11, this pull request will be outdated if you remove the untarring function.

From running setup.go:
```
john$ go run setup.go 
darwin
macos64_odbc_cli.tar.gz
Downloading...
download successful
Creating directory : clidriver/
Creating directory : clidriver/bin/
Creating directory : clidriver/bnd/
Creating directory : clidriver/cfg/
Creating directory : clidriver/cfgcache/
Creating directory : clidriver/conv/
Creating directory : clidriver/db2dump/
Untarring : clidriver/db2profile
Creating directory : clidriver/include/
Creating directory : clidriver/lib/
Creating directory : clidriver/license/
Creating directory : clidriver/msg/
Creating directory : clidriver/msg/en_US.iso88591/
Untarring : clidriver/msg/en_US.iso88591/db2adm.mo
open clidriver/msg/en_US.iso88591/db2adm.mo: permission denied
exit status 1
```
As you can see, creating clidriver/msg/en_US.iso88591/db2adm.mo failed with permission denied. So it's not that I want to write to the files, but rather that the untarring could not write to the files.

**Comment by akhilravuri1** [comment]
For now, you just go to the installer folder and remove *.gz file and clidriver folder and run that setup.go file.  and check whether it is untaring or not.

**Comment by smuda** [comment]
As there are now major changes in the setup.go and the fix to use the tar external command in #11  fixed this problem as well, I close this pull request.

**Pull request closed without merging**
