### PR TITLE
Corrected info message if clidriver is already present

### PR DESCRIPTION
**Pull request by as7664**
If clidriver is already, just add driver path to PATH environment variable and no need to download.

Signed-off-by: Aakash Prajapati <prajapatia7664@gmail.com>

### CODE REVIEW

**Comment by vmathur12** [comment]
@as7664, The issue with the above changes is if user want to update the driver to the latest version, and user can only do this by  removing the environment variables settings and restart the session.

**Comment by as7664** [comment]
> @as7664, The issue with the above changes is if user want to update the driver to the latest version, and user can only do this by removing the environment variables settings and restart the session.

@vmathur12 Okay...If user want to download the driver for the first time, in that case, user will not have any path for the driver. I'll update the README.md to inform user that set the dummy driver path which will be no longer dummy after downloading the driver.

**Comment by vmathur12** [comment]
@as7664 Made changes in the setup.go file to check "db2level" for clidriver is already installed and PATH is set to clidriver/bin. If clidriver is not install it will install the driver even when environment variables are not set. Attached the updated setup.go file, test and let me know your input. Thanks.

[setup.zip](https://github.com/ibmdb/go_ibm_db/files/9981606/setup.zip)

**Comment by vmathur12** [comment]
The code changes for this issue is addressed  in pull request https://github.com/ibmdb/go_ibm_db/pull/193 and hence closing this pull request. Thanks.

**Pull request closed without merging**
